folder_in: '/home/user1/Test7z/tst'
folder_out: '/home/user1/Test7z/out'
folder_ext: '/home/user1/Test7z/folder1'
folder_ext2: '/home/user1/Test7z/folder2'
host: '0.0.0.0'
login: 'user1'
passwd: '111'
type: zip
bs: 1M
count: 5